// 文章分组
const GET_ARTICLE_GROUP = Symbol()
const ADD_ARTICLE_GROUP = Symbol()
const DELETE_ARTICLE_GROUP = Symbol()
const UPDATE_ARTICLE_GROUP = Symbol()

export {
    GET_ARTICLE_GROUP,
    ADD_ARTICLE_GROUP,
    DELETE_ARTICLE_GROUP,
    UPDATE_ARTICLE_GROUP
}