// 文章分组
const GET_ARTICLE_GROUP = Symbol()
const ADD_ARTICLE_GROUP = Symbol()
const DELETE_ARTICLE_GROUP = Symbol()
const UPDATE_ARTICLE_GROUP = Symbol()

// 文章链接
const GET_EXTEND_LINK = Symbol()
const ADD_EXTEND_LINK = Symbol()
const DELETE_EXTEND_LINK = Symbol()
const UPDATE_EXTEND_LINK = Symbol()


export {
    GET_ARTICLE_GROUP,
    ADD_ARTICLE_GROUP,
    DELETE_ARTICLE_GROUP,
    UPDATE_ARTICLE_GROUP,

    GET_EXTEND_LINK,
    ADD_EXTEND_LINK,
    DELETE_EXTEND_LINK,
    UPDATE_EXTEND_LINK
}